name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
   
    
  DeployStaging:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
    steps:
      - name: Deploy
        run: echo I am deploying! 
            
  DeployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Prod
    steps:
      - name: Deploy
        run: echo I am deploying! 
      - uses: actions/checkout@v2
      - name: Zip Folder
        run: tar cfzv release.tar .
      - name: Release to Github
        run: echo "Release"
      - name: Download a Build Artifact
      - uses: actions/upload-artifact@v1
        with:
          name: Zip Folder
          path: ${{ github.workspace }}/release.tar
    
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: Zip Folder
          path: path/to/artifacts
    
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
    
