name: CI + CD + manual

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#  workflow_dispatch:

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
    
  DeployDev:
    name: Deploy to Dev 
#    if: github.event_name == 'pull_request'
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: windows-latest
    environment: 
      name: Dev
    steps:
      - name: Deploy
        run: echo I am deploying! 

            
  DeployProd:
    name: Deploy to Production 
    needs: [DeployDev]
    runs-on: windows-latest
#    environment: 
#      name: Prod
    steps:
      - name: Deploy
        run: echo I am deploying! 
      - uses: actions/checkout@v2
      - name: Zip Folder
        run: tar cfzv release.tar .
      - name: Release to Github
        run: echo "Release"
      - name: Download a Build Artifact
      - uses: actions/upload-artifact@v1
        with:
          name: Zip Folder
          path: ${{ github.workspace }}/release.tar
    
      - uses: actions/download-artifact@v1
        with:
          name: Zip Folder
          path: path/to/artifacts
    
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
        
    
