on: [push]
name: NewWorkflow
jobs:
  build:
    runs-on: ubuntu-latest

      
# The Secrect Actions GitHub example has three steps
    steps:
  # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.SECRET_TOKEN }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g' 
  # Use a GitHub Actions secret variable in a bash shell
      - name: Step 2 - GitHub Action if statement (true)
      
        env: 
          WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
      - if:  env.WHO_TO_TRUST == 'TrustNo1'
        name: if
 #      run: |echo "I know what the secret token is!" 
        run: |
          echo "If Statement"
          - uses: actions/checkout@v1
            run: tar cfzv release.tar .
 #     - name: Zip Folder
        
      - name: Release to Github
        run: echo "Release"



      









