on: [push]
name: NewWorkflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Log in with Azure
    # Use a GitHub Actions secret variable in a bash shell
    - name: Step 2 - GitHub Action if statement (true)
      env: 
      WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
      if:  env.WHO_TO_TRUST == 'TrustNo1'
      run: echo "I know what the secret token is!"
